# The engine half of the bytecode cache key.
#
# Hashes every file under compiler/ and system/ (the compiler, the interpreter,
# and the built-in registry). CMake's custom command runs this script; the
# backend's MSBuild project computes the same rule in an inline task
# (EngineFingerprint in backend.vcxproj), so a Windows build needs no cmake.
# Change one, change the other: the two must give one hash. The header is written
# only when the hash changes: a timestamp that moved on every build would
# recompile the backend for nothing.
#
#   cmake -DOES_COMPILER_DIR=... -DOES_SYSTEM_DIR=... -DOES_BACKEND_DIR=...
#         -DOES_FINGERPRINT_OUT=.../engineFingerprintBuild.h
#         -P engineFingerprint.cmake
#
# A test passes OES_SUBSTITUTE_REL (a path relative to the backend directory,
# forward slashes) and OES_SUBSTITUTE_FILE to hash that path's bytes from
# another file. That is how a built-in change is shown to move the key without
# editing the tree.

if(NOT DEFINED OES_COMPILER_DIR OR NOT DEFINED OES_SYSTEM_DIR OR NOT DEFINED OES_BACKEND_DIR OR NOT DEFINED OES_FINGERPRINT_OUT)
	message(FATAL_ERROR "engineFingerprint.cmake needs OES_COMPILER_DIR, OES_SYSTEM_DIR, OES_BACKEND_DIR and OES_FINGERPRINT_OUT")
endif()

file(GLOB_RECURSE _oes_fp_files LIST_DIRECTORIES false
	"${OES_COMPILER_DIR}/*"
	"${OES_SYSTEM_DIR}/*")
set(_oes_fp_rels "")
foreach(_oes_fp_file IN LISTS _oes_fp_files)
	file(RELATIVE_PATH _oes_fp_rel "${OES_BACKEND_DIR}" "${_oes_fp_file}")
	string(REPLACE "\\" "/" _oes_fp_rel "${_oes_fp_rel}")
	if(_oes_fp_rel MATCHES "(^|/)CMakeFiles/")
		continue()
	endif()
	list(APPEND _oes_fp_rels "${_oes_fp_rel}")
endforeach()
list(SORT _oes_fp_rels)

set(_oes_fp_payload "")
foreach(_oes_fp_rel IN LISTS _oes_fp_rels)
	if(DEFINED OES_SUBSTITUTE_REL AND _oes_fp_rel STREQUAL "${OES_SUBSTITUTE_REL}")
		file(READ "${OES_SUBSTITUTE_FILE}" _oes_fp_bytes HEX)
	else()
		file(READ "${OES_BACKEND_DIR}/${_oes_fp_rel}" _oes_fp_bytes HEX)
	endif()
	string(APPEND _oes_fp_payload "${_oes_fp_rel}\n${_oes_fp_bytes}\n")
endforeach()
string(SHA256 _oes_fp_hash "${_oes_fp_payload}")

set(_oes_fp_body "#ifndef __ENGINE_FINGERPRINT_BUILD_H__
#define __ENGINE_FINGERPRINT_BUILD_H__

// Generated by compiler/engineFingerprint.cmake. Do not edit.
// The hash is every file under compiler/ and system/. The bytecode cache key
// carries it, so a compiler change or a new built-in misses the old rows.

inline constexpr char kEngineFingerprint[] = \"${_oes_fp_hash}\";

#endif
")

if(EXISTS "${OES_FINGERPRINT_OUT}")
	file(READ "${OES_FINGERPRINT_OUT}" _oes_fp_old)
	if(_oes_fp_old STREQUAL "${_oes_fp_body}")
		return()
	endif()
endif()
get_filename_component(_oes_fp_dir "${OES_FINGERPRINT_OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_oes_fp_dir}")
file(WRITE "${OES_FINGERPRINT_OUT}" "${_oes_fp_body}")
