#include "firebirdReplicationConfig.h"
#include "backend/diagnostics/journal.h"   // ibJournal — this TU does not pull in backend_core.h

#include <wx/file.h>
#include <wx/filename.h>
#include <wx/log.h>

namespace {

// Reject any string heading into the generated config that could
// break the line-oriented format: newlines, the `}` section
// terminator, or the `#` comment marker. FB's parser would either
// reject or silently misinterpret such input; better to fail fast.
bool LooksSafeForConfig(const wxString& s) {
	for (wxString::const_iterator it = s.begin(); it != s.end(); ++it) {
		const wxUniChar c = *it;
		if (c == wxT('\n') || c == wxT('\r')
		 || c == wxT('}')  || c == wxT('{')
		 || c == wxT('#')) {
			return false;
		}
	}
	return true;
}

} // namespace

wxString ibFirebirdReplicationConfig::Build(
	const wxString& databasePath,
	const wxString& journalDir,
	const std::vector<Peer>& peers)
{
	// FB replication.conf is line-oriented, sections per database
	// delimited by `database = <path>` headers. We generate exactly
	// one section per call; callers writing multi-DB configs
	// concatenate Build outputs.
	//
	// Format reference (Firebird 4.0+ replication framework):
	//
	//     database = D:\office.fdb
	//     {
	//         journal_directory = D:\office.repl
	//         log_segment_size = 16M
	//         log_segment_count = 8
	//         sync_replica = host1:3050 / SYSDBA : password
	//         sync_replica = host2:3050 / SYSDBA : password
	//     }
	//
	// SECURITY: peer passwords land here in plain text. The file
	// must be readable only by the FB process owner; back it up
	// with appropriate file-system ACLs. FB doesn't support
	// encrypted credentials in replication.conf as of FB 5.x —
	// this is an engine constraint, not an OES choice.
	//
	// Synchronous vs async — we use sync_replica for the strongest
	// consistency the framework offers (each peer must ack before
	// commit completes). For LAN-mesh of <30 peers this is the
	// right default; long-distance replication should switch to
	// async_replica which the framework also supports.

	// Input validation — reject paths / peer entries that would
	// break the line-oriented format. Empty string on rejection so
	// callers don't ship a half-generated config.
	if (!LooksSafeForConfig(databasePath) || !LooksSafeForConfig(journalDir)) {
		ibJournalError(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: databasePath or ")
		           wxT("journalDir contains characters unsafe for ")
		           wxT("replication.conf (newline / brace / hash)"));
		return wxEmptyString;
	}

	wxString out;
	out << wxT("# Generated by ibFirebirdReplicationConfig - do not edit by hand.\n");
	out << wxT("# Driver regenerates this file on every startup from mesh.conf.\n\n");

	out << wxT("database = ") << databasePath << wxT("\n");
	out << wxT("{\n");
	out << wxT("    journal_directory = ") << journalDir << wxT("\n");
	out << wxT("    log_segment_size = 16M\n");
	out << wxT("    log_segment_count = 8\n");

	for (const Peer& p : peers) {
		// Format: `host:port / user : password`. Default credentials
		// SYSDBA / masterkey if caller didn't override — typical for
		// LAN mesh with shared service account.
		const wxString user = p.username.IsEmpty() ? wxT("SYSDBA") : p.username;
		const wxString pwd  = p.password.IsEmpty() ? wxT("masterkey") : p.password;

		if (!LooksSafeForConfig(p.address)
		 || !LooksSafeForConfig(user)
		 || !LooksSafeForConfig(pwd)) {
			ibJournalError(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: peer entry contains ")
			           wxT("characters unsafe for replication.conf - skipped"));
			continue;
		}

		// Warn on default credentials in any real deployment — config
		// is plaintext on disk and SYSDBA/masterkey is the FB OOTB
		// secret that every attacker tries first.
		if (pwd == wxT("masterkey")) {
			ibJournalWarning(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: peer %s uses ")
			             wxT("default 'masterkey' password - change before ")
			             wxT("production deploy"), p.address);
		}

		out << wxT("    sync_replica = ") << p.address
		    << wxT(" / ") << user
		    << wxT(" : ") << pwd
		    << wxT("\n");
	}

	out << wxT("}\n");
	return out;
}

bool ibFirebirdReplicationConfig::WriteToRuntimeDir(
	const wxString& fbRuntimeDir,
	const wxString& content)
{
	if (fbRuntimeDir.IsEmpty()) {
		ibJournalError(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: FB runtime dir not set"));
		return false;
	}

	// Atomic write: stage into `<path>.tmp`, then rename over the
	// final target. Prevents a crash mid-Write from leaving a
	// partial replication.conf that FB would reject on next start.
	wxFileName fn(fbRuntimeDir, wxT("replication.conf"));
	const wxString finalPath = fn.GetFullPath();
	const wxString tempPath  = finalPath + wxT(".tmp");

	{
		wxFile f;
		if (!f.Open(tempPath, wxFile::write)) {
			ibJournalError(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: cannot open %s"),
			           tempPath);
			return false;
		}
		// wxScopedCharBuffer carries its own length — strlen() on
		// the raw bytes would truncate at any embedded NUL (defensive;
		// our generated content has none, but new fields could).
		const auto utf8 = content.utf8_str();
		const size_t len = utf8.length();
		if (f.Write(utf8.data(), len) != len) {
			ibJournalError(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: short write on %s"),
			           tempPath);
			f.Close();
			wxRemoveFile(tempPath);
			return false;
		}
		if (!f.Close()) {
			ibJournalError(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: close failed on %s"),
			           tempPath);
			wxRemoveFile(tempPath);
			return false;
		}
	}

	// wxRenameFile overwrites the destination by default — atomic on
	// the same volume on every supported platform (Win32 / POSIX).
	if (!wxRenameFile(tempPath, finalPath, /*overwrite=*/true)) {
		ibJournalError(wxT("db.firebird"),wxT("ibFirebirdReplicationConfig: rename %s -> %s failed"),
		           tempPath, finalPath);
		wxRemoveFile(tempPath);
		return false;
	}
	return true;
}
