#include "dataReport.h"

/* PNG */
static const wxString s_report_64_png = wxT("iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABpklEQVR4nOybvUoDQRDH/3v6ChZBJbZaiPgBQZuzsBNB8QUEBUvBQrARhPT2ClZWPoKFaYSAGMRCESwEFR/BznEDCgcm2T1uyO1m5tfd3hR7P25md+4jgXASCEcFQDjDroD5xXSTiI6NMZMoETuHJyJTbzUbF2BkyBVQGate2oufQsnYOYwYg43K6MTH5/trC0w4UyCEi89iEpzO1dJtMBFlDfiVsAsGjCvA1gDKHt/eXKOfLCwtdz1H39i5azbOUICoVwGOdIh+GSwqIToBhwf7/8aKSIhOwPraKquEKFOAU0K0NYBLQtRFkEOCsxcIjV77gixtCbO19MvVOwx0N2h7h7orJro7IA9WQNUVo88DEDh5ew/fGvGH3gEIlJnzlY7j91tX4EQfikI4KgDC0VUAfWZ876Hj+NvJNMpAUwDCUQEQjgqAcHQfACZCW9990RSAcFQAhKMCIBwVAOGoAAhHewEw4bvn943jfgPUDU0BCEcFQDgqAMLRfQBykvcbnNDRFHAFENEjIsVn7j4/TR0R4QXx8dyeuyvI+c/QoKM1AMIRL+AHAAD//6GNUIwAAAAGSURBVAMAwBRdkVMdDg8AAAAASUVORK5CYII=");

wxIcon ibValueMetaObjectReport::GetIcon() const
{
	return GetIconGroup();
}

wxIcon ibValueMetaObjectReport::GetIconGroup()
{
	static wxIcon icon =
		ibBackendPicture::GetIconFromBase64(s_report_64_png, wxSize(16, 16));

	return icon;
}
