#ifndef _MAINFRAME_DEFS_H__
#define _MAINFRAME_DEFS_H__

enum {
	wxID_DESIGNER_UPDATE_METADATA = 10000,

	wxID_DESIGNER_DEBUG_START,
	wxID_DESIGNER_DEBUG_START_WITHOUT_DEBUGGING,
	wxID_DESIGNER_DEBUG_ATTACH_FOR_DEBUGGING,
	wxID_DESIGNER_DEBUG_EDIT_POINT,
	wxID_DESIGNER_DEBUG_STEP_OVER,
	wxID_DESIGNER_DEBUG_STEP_INTO,
	wxID_DESIGNER_DEBUG_PAUSE ,
	wxID_DESIGNER_DEBUG_STOP_DEBUGGING ,
	wxID_DESIGNER_DEBUG_STOP_PROGRAM,
	wxID_DESIGNER_DEBUG_NEXT_POINT,
	wxID_DESIGNER_DEBUG_REMOVE_ALL_DEBUGPOINTS, 

	wxID_DESIGNER_CONFIGURATION_RETURN_DATABASE,

	wxID_DESIGNER_CONFIGURATION_LOAD,
	wxID_DESIGNER_CONFIGURATION_SAVE,

	wxID_DESIGNER_ABOUT,
	wxID_DESIGNER_END
};

enum {
	wxID_ENTERPRISE_ALL_OPERATIONS = wxID_DESIGNER_END + 1,

	wxID_ENTERPRISE_ABOUT,
	wxID_ENTERPRISE_END
};

//menu  
enum {
	wxID_APPLICATION_DEBUG = wxID_ENTERPRISE_END + 1,
	wxID_APPLICATION_SETTING,
	wxID_APPLICATION_USERS,
	wxID_APPLICATION_ACTIVE_USERS,
};

#endif 