/////////////////////////////////////////////////////////////////////////////
// byokEnv implementation. See header for the contract.
/////////////////////////////////////////////////////////////////////////////

#include "byokEnv.h"
#include "pluginsConfig.h"

#include <wx/filename.h>
#include <wx/dir.h>
#include <wx/log.h>

#include <fstream>
#include <sstream>

#ifndef _WIN32
#include <sys/stat.h>
#include <unistd.h>
#endif

namespace byokEnv {
namespace {

// Strip leading + trailing whitespace.
std::string Trim(const std::string& s)
{
	const auto first = s.find_first_not_of(" \t\r\n");
	if (first == std::string::npos) return std::string();
	const auto last = s.find_last_not_of(" \t\r\n");
	return s.substr(first, last - first + 1);
}

// Decode a possibly-double-quoted dotenv value. Bare values pass
// through (after Trim). Quoted values respect \n \r \t \" \\ escapes.
std::string DecodeValue(const std::string& raw)
{
	const std::string t = Trim(raw);
	if (t.size() >= 2 && t.front() == '"' && t.back() == '"') {
		std::string out;
		out.reserve(t.size());
		for (std::size_t i = 1; i + 1 < t.size(); ++i) {
			const char c = t[i];
			if (c == '\\' && i + 2 < t.size()) {
				const char n = t[i + 1];
				switch (n) {
				case 'n':  out += '\n'; ++i; continue;
				case 'r':  out += '\r'; ++i; continue;
				case 't':  out += '\t'; ++i; continue;
				case '"':  out += '"';  ++i; continue;
				case '\\': out += '\\'; ++i; continue;
				}
			}
			out += c;
		}
		return out;
	}
	return t;
}

// Parse one .env file into a KeyMap. Comments (#-prefixed) and blank
// lines are skipped. Lines missing '=' silently ignored.
KeyMap ParseEnvFile(const wxString& path)
{
	KeyMap m;
	std::ifstream f(std::string(path.utf8_str()), std::ios::binary);
	if (!f.is_open()) return m;
	std::string line;
	while (std::getline(f, line)) {
		// Strip trailing \r — handles CRLF on cross-platform files.
		if (!line.empty() && line.back() == '\r') line.pop_back();
		const std::string trimmed = Trim(line);
		if (trimmed.empty() || trimmed[0] == '#') continue;
		const auto eq = trimmed.find('=');
		if (eq == std::string::npos) continue;
		const std::string key = Trim(trimmed.substr(0, eq));
		const std::string val = DecodeValue(trimmed.substr(eq + 1));
		if (key.empty()) continue;
		m[key] = val;
	}
	return m;
}

// Directory containing per-plugin .env files. Mirrors the plugins.json5
// location so admins can manage all secrets in one place.
wxString GetEnvDir()
{
	wxFileName cfg(pluginsConfig::GetConfigPath());
	return cfg.GetPath();
}

#ifndef _WIN32
// Warn when permissions on `path` are looser than mode 0600.
void WarnIfPermsLoose(const wxString& path)
{
	struct stat st{};
	if (::stat(std::string(path.utf8_str()).c_str(), &st) != 0) return;
	const mode_t mode = st.st_mode & 0777;
	if (mode & 0077) {
		wxLogWarning(wxT("byokEnv: %s has mode 0%o (recommended 0600 — others may read your API key)"),
		             path, static_cast<unsigned>(mode));
	}
}

void TightenPerms(const wxString& path)
{
	::chmod(std::string(path.utf8_str()).c_str(), S_IRUSR | S_IWUSR);
}
#else
void WarnIfPermsLoose(const wxString&) {}
void TightenPerms(const wxString&) {
	// Windows ACL tightening would go through SetSecurityInfo +
	// builtin\Administrators / current-user. Phase 4.2 ships the file
	// in default ACL (NTFS inherits from parent — typically already
	// user-only inside %APPDATA%). A future commit can add SetSecurityInfo
	// for environments where %APPDATA% is itself shared.
}
#endif

} // namespace

wxString GetEnvFilePath(const std::string& pluginId)
{
	wxFileName fn(GetEnvDir(), wxString::FromUTF8(pluginId) + wxT(".env"));
	return fn.GetFullPath();
}

PluginEnv LoadAll()
{
	PluginEnv all;
	const wxString dir = GetEnvDir();
	if (!wxDirExists(dir)) return all;

	wxArrayString files;
	wxDir::GetAllFiles(dir, &files, wxT("*.env"), wxDIR_FILES);
	for (const wxString& path : files) {
		WarnIfPermsLoose(path);
		wxFileName fn(path);
		const std::string pluginId = std::string(fn.GetName().utf8_str());
		if (pluginId.empty()) continue;
		all[pluginId] = ParseEnvFile(path);
	}
	return all;
}

int Save(const std::string& pluginId, const KeyMap& keys)
{
	if (pluginId.empty()) return -1;
	const wxString path = GetEnvFilePath(pluginId);

	wxFileName fn(path);
	if (!fn.Mkdir(0700, wxPATH_MKDIR_FULL)) {
		// Mkdir returns false when dir already exists — not an error.
		// Real failures show via the subsequent open() error.
	}

	std::ofstream f(std::string(path.utf8_str()), std::ios::binary | std::ios::trunc);
	if (!f.is_open()) {
		wxLogWarning(wxT("byokEnv: failed to write %s"), path);
		return -1;
	}
	f << "# Generated by OES — do not commit. Permissions: 0600.\n";
	for (const auto& [k, v] : keys) {
		// Always quote values to round-trip control chars / spaces.
		f << k << "=\"";
		for (char c : v) {
			switch (c) {
			case '\\': f << "\\\\"; break;
			case '"':  f << "\\\""; break;
			case '\n': f << "\\n";  break;
			case '\r': f << "\\r";  break;
			case '\t': f << "\\t";  break;
			default:   f << c;
			}
		}
		f << "\"\n";
	}
	f.close();

	TightenPerms(path);
	return 0;
}

std::string Get(const PluginEnv& env, const std::string& pluginId,
                 const std::string& key)
{
	auto pit = env.find(pluginId);
	if (pit == env.end()) return std::string();
	auto kit = pit->second.find(key);
	if (kit == pit->second.end()) return std::string();
	return kit->second;
}

} // namespace byokEnv
